{{- if .Values.services.object_store.minio }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: minio-service
  name: minio-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: minio-service
    spec:
      containers:
      - args:
        - server
        - /data
        env:
        - name: MINIO_BROWSER
          value: {{ .Values.services.object_store.browser | quote }}
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "budibase.fullname" . }}
              key: objectStoreAccess
          # value: {{ .Values.services.object_store.accessKey }}
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "budibase.fullname" . }}
              key: objectStoreSecret
          # value: {{ .Values.services.object_store.secretKey }}
        image: minio/minio
        imagePullPolicy: ""
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:9000/minio/health/live
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 20
        name: minio-service
        ports:
        - containerPort: {{ .Values.services.object_store.port }}
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: minio-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-data
status: {}
{{- end }}