version: "3"

# optional ports are specified throughout for more advanced use cases.

services:
  dev-service:
    container_name: budi-dev
    restart: on-failure
    image: budibase/dependencies
    ports:
      - "${MINIO_PORT}:9000"
      - "9001:9001"
      - "${COUCH_DB_PORT}:5984"
      - "${REDIS_PORT}:6379"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      COUCHDB_PASSWORD: ${COUCH_DB_PASSWORD}
      COUCHDB_USER: ${COUCH_DB_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - dev_data:/data

  proxy-service:
    container_name: budi-nginx-dev
    restart: on-failure
    image: budibase/proxy:latest
    volumes:
      - ./nginx.dev.conf:/etc/nginx/templates/nginx.conf.template
      - ./proxy/error.html:/usr/share/nginx/html/error.html
    ports:
      - "${MAIN_PORT}:10000"
    depends_on:
      - dev-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PROXY_ADDRESS=host.docker.internal

volumes:
  dev_data:
    driver: local