apiVersion: v2
name: budibase
description: >-
  Budibase is an open source low-code platform, helping thousands of teams build
  apps for their workplace in minutes.
keywords:
  - low-code
  - database
  - cluster
sources:
  - https://github.com/Budibase/budibase
  - https://budibase.com
type: application
version: 0.2.4
appVersion: 1.0.20
dependencies:
  - name: couchdb
    version: 3.3.4
    repository: https://apache.github.io/couchdb-helm
    condition: services.couchdb.enabled
  - name: ingress-nginx
    version: 3.35.0
    repository: https://github.com/kubernetes/ingress-nginx
    condition: ingress.nginx
