name: Budibase Cloud Deploy

on:
 workflow_dispatch:
  inputs:
    version:
      description: Budibase release version. For example - 1.0.0
      required: false

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull values.yaml from budibase-infra
        run: | 
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \                                                                                [c3a7a9d12]
          -H 'Accept: application/vnd.github.v3.raw' \
          -o values.production.yaml \
          -L https://api.github.com/repos/budibase/budibase-infra/contents/kubernetes/values.yaml
      
      - name: Get the latest budibase release version if not specifically set
        if: ${{ !github.event.inputs.version }}
        id: version
        run: | 
           sudo apt-get install -y jq 
           release_version=$(cat lerna.json | jq -r '.version')
           echo "::set-output name=release_version::$release_version"

      - name: Deploy to EKS
        uses: craftech-io/eks-helm-deploy-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          cluster-name: budibase-eks-production
          config-files: values.production.yaml
          chart-path: charts/budibase
          namespace: budibase
          values: appVersion=v${{ github.event.inputs.version || github.steps.version.outputs.release_version }}
          name: budibase-prod