name: Budibase Cloud Deploy

on:
 workflow_dispatch:
  inputs:
    version:
      description: Budibase release version. For example - 1.0.0
      required: false

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull values.yaml from budibase-infra
        run: | 
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H 'Accept: application/vnd.github.v3.raw' \
          -o values.production.yaml \
          -L https://api.github.com/repos/budibase/budibase-infra/contents/kubernetes/values.yaml
      
      - name: Get the latest budibase release version
        id: version
        run: | 
          if [ -z "${{ github.event.inputs.version }}" ]; then
            release_version=$(cat lerna.json | jq -r '.version')
          else
            release_version=${{ github.event.inputs.version }}
          fi
          echo "::set-output name=release_version::$release_version"
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Deploy to EKS
        uses: craftech-io/eks-helm-deploy-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          cluster-name: budibase-eks-production
          config-files: values.production.yaml
          chart-path: charts/budibase
          namespace: budibase
          values: appVersion=v${{ github.steps.version.outputs.release_version }}
          name: budibase-prod