name: Budibase Release (Pro)

#  Temporary pipeline - eventualy this will be merged with the regular one

on:
  push:
    branches:
      - pro-master
    paths:
      - ".aws/**"
      - ".github/**"
      - "charts/**"
      - "packages/**"
      - "scripts/**"
      - "package.json"
      - "yarn.lock"
      - "package.json"
      - "yarn.lock"

env:
  POSTHOG_TOKEN: ${{ secrets.POSTHOG_TOKEN }}
  INTERCOM_TOKEN: ${{ secrets.INTERCOM_TOKEN }}
  POSTHOG_URL: ${{ secrets.POSTHOG_URL }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn
      - run: yarn bootstrap
      - run: yarn lint
      - run: yarn build
      - run: yarn test

      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Build/release Docker images
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          yarn build:docker:pro
          yarn release:docker:pro ${BUDIBASE_RELEASE_VERSION}
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_API_KEY }}
          BUDIBASE_RELEASE_VERSION: ${{ steps.previoustag.outputs.tag }}
