name: Budibase Release Helm Charts

on:
 workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      # - run: yarn release:helm
      #   env:
      #     BUDIBASE_RELEASE_VERSION: ${{ steps.previoustag.outputs.tag }}

      - name: Configure Git
        run: |
          git config user.name "Budibase Helm Bot"
          git config user.email "<>"
      
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"