name: Budibase Release

on: 
 push:
    branches:
      - master
      
jobs:
  release:
    runs-on: ubuntu-latest 
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn 
      - run: yarn lint 
      - run: yarn bootstrap 
      - run: yarn build 
        env:
          POSTHOG_TOKEN: ${{ secrets.POSTHOG_TOKEN }}
          POSTHOG_URL: ${{ secrets.POSTHOG_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - run: yarn test

      # - name: Publish budibase packages to NPM
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: yarn release

      - name: Build/release Docker images
        run: | 
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          yarn build
          yarn build:docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_API_KEY }}
